# ─────────────────────────────────────────
# SERVER
# ─────────────────────────────────────────
server.port=8081

# ─────────────────────────────────────────
# DATASOURCE — SQL Server (account-db)
# ─────────────────────────────────────────
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=account_db;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Postgres123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Tắt Docker Compose auto-detection để tránh conflict 2 db
spring.docker.compose.enabled=false

# ─────────────────────────────────────────
# KAFKA
# ─────────────────────────────────────────
spring.kafka.bootstrap-servers=localhost:9092,localhost:9094,localhost:9095
spring.kafka.consumer.group-id=banking-group
spring.kafka.consumer.auto-offset-reset=earliest

# ─────────────────────────────────────────
# REDIS
# ─────────────────────────────────────────
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis123

# ─────────────────────────────────────────
# LOGGING
# ─────────────────────────────────────────
logging.level.com.bankingeconomy=DEBUG
logging.level.org.springframework.kafka=INFO