# SERVER & APPLICATION
spring.application.name=WEBBANKING
server.port=8084

# ==================== SQL SERVER ====================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BankingEconomy;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Postgres123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ==================== REDIS ====================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis123

# ==================== KAFKA ====================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=banking-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ==================== JWT ====================
jwt.secret-key=eyJhbGciOiJIUzUxMiJ9.ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0.ZjuawnJ2EoXlKYbNRffaOHKQikY7wPWzIYCePxB7512jl2EjIUg2Pz_ShjVBssd34eOEJ9n9gstU9D3oVRdL8
jwt.expiration=86400000

# ==================== DOCKER COMPOSE ====================
logging.level.com.bankingeconomy=DEBUG
logging.level.org.springframework.kafka=INFO
spring.docker.compose.enabled=false
spring.docker.compose.file=compose.yaml

hadoop.enabled=true