# SERVER & APPLICATION
spring.application.name=WEBBANKING
server.port=8084

spring.datasource.central.jdbc-url=jdbc:sqlserver://localhost:1433;databaseName=BankingEconomy;encrypt=false;trustServerCertificate=true
spring.datasource.central.username=sa
spring.datasource.central.password=Postgres123!
spring.datasource.central.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.north.jdbc-url=jdbc:sqlserver://10.3.175.188:1433;databaseName=WebBanking_North;encrypt=false;trustServerCertificate=true
spring.datasource.north.username=sa
spring.datasource.north.password=Postgres123!
spring.datasource.north.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.mid.jdbc-url=jdbc:sqlserver://10.3.175.232:1433;databaseName=WebBanking_Mid;encrypt=false;trustServerCertificate=true
spring.datasource.mid.username=sa
spring.datasource.mid.password=Postgres123!
spring.datasource.mid.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.south.jdbc-url=jdbc:sqlserver://10.3.175.245:1433;databaseName=WebBanking_South;encrypt=false;trustServerCertificate=true
spring.datasource.south.username=sa
spring.datasource.south.password=Postgres123!
spring.datasource.south.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.open-in-view=false

# ==================== REDIS ====================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=redis123

# ==================== KAFKA ====================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=banking-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# 1. Kich hoat che do Consumer nhan theo lo (List)
spring.kafka.listener.type=batch

# 2. Quy dinh so luong DTO toi da duoc muc ra trong 1 lo
spring.kafka.consumer.max-poll-records=1000
spring.kafka.consumer.properties.fetch.max.wait.ms=60000

# ==================== JWT ====================
jwt.secret-key=eyJhbGciOiJIUzUxMiJ9.ew0KICAic3ViIjogIjEyMzQ1Njc4OTAiLA0KICAibmFtZSI6ICJBbmlzaCBOYXRoIiwNCiAgImlhdCI6IDE1MTYyMzkwMjINCn0.ZjuawnJ2EoXlKYbNRffaOHKQikY7wPWzIYCePxB7512jl2EjIUg2Pz_ShjVBssd34eOEJ9n9gstU9D3oVRdL8
jwt.expiration=86400000

# ==================== DOCKER COMPOSE ====================
logging.level.com.bankingeconomy=DEBUG
logging.level.org.springframework.kafka=INFO
spring.docker.compose.enabled=false
spring.docker.compose.file=compose.yaml

hadoop.enabled=true
