USE [master]
GO
/****** Object:  Database [WebBanking_South]    Script Date: 5/12/26 3:39:33PM ******/
CREATE DATABASE [WebBanking_South]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WebBanking_South', FILENAME = N'/var/opt/mssql/data/WebBanking_South.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WebBanking_South_log', FILENAME = N'/var/opt/mssql/data/WebBanking_South_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WebBanking_South].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [WebBanking_South] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [WebBanking_South] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [WebBanking_South] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [WebBanking_South] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [WebBanking_South] SET ARITHABORT OFF 
GO
ALTER DATABASE [WebBanking_South] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [WebBanking_South] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [WebBanking_South] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [WebBanking_South] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [WebBanking_South] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [WebBanking_South] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [WebBanking_South] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [WebBanking_South] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [WebBanking_South] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [WebBanking_South] SET  ENABLE_BROKER 
GO
ALTER DATABASE [WebBanking_South] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [WebBanking_South] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [WebBanking_South] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [WebBanking_South] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [WebBanking_South] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [WebBanking_South] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [WebBanking_South] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [WebBanking_South] SET RECOVERY FULL 
GO
ALTER DATABASE [WebBanking_South] SET  MULTI_USER 
GO
ALTER DATABASE [WebBanking_South] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [WebBanking_South] SET DB_CHAINING OFF 
GO
ALTER DATABASE [WebBanking_South] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [WebBanking_South] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [WebBanking_South] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'WebBanking_South', N'ON'
GO
ALTER DATABASE [WebBanking_South] SET QUERY_STORE = ON
GO
ALTER DATABASE [WebBanking_South] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO
USE [WebBanking_South]
GO
ALTER DATABASE SCOPED CONFIGURATION SET ACCELERATED_PLAN_FORCING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ADAPTIVE_JOINS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET CE_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DOP_FEEDBACK = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET DW_COMPATIBILITY_LEVEL = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_ONLINE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_RESUMABLE = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET EXEC_QUERY_STATS_FOR_SCALAR_FUNCTIONS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET FORCE_SHOWPLAN_RUNTIME_PARAMETER_COLLECTION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET GLOBAL_TEMPORARY_TABLE_AUTO_DROP = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ISOLATE_SECURITY_POLICY_CARDINALITY = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LAST_QUERY_PLAN_STATS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEDGER_DIGEST_STORAGE_ENDPOINT = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LIGHTWEIGHT_QUERY_PROFILING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERCENTILE_GRANT = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MEMORY_GRANT_FEEDBACK_PERSISTENCE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZED_PLAN_FORCING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZE_FOR_AD_HOC_WORKLOADS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SENSITIVE_PLAN_OPTIMIZATION = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PAUSED_RESUMABLE_INDEX_ABORT_DURATION_MINUTES = 1440;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET TSQL_SCALAR_UDF_INLINING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET VERBOSE_TRUNCATION_WARNINGS = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_PROCEDURE_EXECUTION_STATISTICS = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET XTP_QUERY_EXECUTION_STATISTICS = OFF;
GO
USE [WebBanking_South]
GO
/****** Object:  Table [dbo].[accounts]    Script Date: 5/12/26 3:39:34PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[accounts](
	[balance] [float] NOT NULL,
	[created_at] [datetime2](7) NULL,
	[id] [uniqueidentifier] NOT NULL,
	[user_id] [uniqueidentifier] NULL,
	[account_number] [varchar](20) NULL,
	[status] [varchar](255) NULL,
 CONSTRAINT [PK__accounts__3213E83F9CEA8BFB] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[audit_logs]    Script Date: 5/12/26 3:39:36PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[audit_logs](
	[id] [uniqueidentifier] NOT NULL,
	[amount] [float] NULL,
	[created_at] [datetime2](7) NOT NULL,
	[description] [varchar](255) NULL,
	[fail_reason] [varchar](255) NULL,
	[from_account_number] [varchar](255) NULL,
	[processed_at] [datetime2](7) NULL,
	[status] [varchar](255) NULL,
	[to_account_number] [varchar](255) NULL,
	[transaction_id] [varchar](255) NOT NULL,
 CONSTRAINT [PK__audit_lo__3213E83F5D489F3A] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[beneficiaries]    Script Date: 5/12/26 3:39:36PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[beneficiaries](
	[id] [uniqueidentifier] NOT NULL,
	[target_account_id] [uniqueidentifier] NULL,
	[user_id] [uniqueidentifier] NULL,
 CONSTRAINT [PK__benefici__3213E83F65E19258] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[notifications]    Script Date: 5/12/26 3:39:36PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[notifications](
	[is_read] [bit] NULL,
	[created_at] [datetime2](7) NULL,
	[id] [uniqueidentifier] NOT NULL,
	[user_id] [uniqueidentifier] NULL,
	[message] [varchar](20) NULL,
	[type] [varchar](255) NULL,
 CONSTRAINT [PK__notifica__3213E83FF25E6F64] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[saved_receiver_accounts]    Script Date: 5/12/26 3:39:36PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[saved_receiver_accounts](
	[id] [uniqueidentifier] NOT NULL,
	[created_at] [datetime2](7) NOT NULL,
	[updated_at] [datetime2](7) NOT NULL,
	[target_account_id] [uniqueidentifier] NULL,
	[user_id] [uniqueidentifier] NULL,
 CONSTRAINT [PK__saved_re__3213E83F808701F6] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[transactions]    Script Date: 5/12/26 3:39:36PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[transactions](
	[amount] [float] NOT NULL,
	[created_at] [datetime2](7) NULL,
	[from_account_id] [uniqueidentifier] NULL,
	[id] [uniqueidentifier] NOT NULL,
	[to_account_id] [uniqueidentifier] NULL,
	[status] [varchar](20) NULL,
	[description] [varchar](255) NULL,
 CONSTRAINT [PK__transact__3213E83F35940A7D] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[users]    Script Date: 5/12/26 3:39:36PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[users](
	[created_at] [datetime2](7) NOT NULL,
	[id] [uniqueidentifier] NOT NULL,
	[district] [nvarchar](255) NULL,
	[email] [varchar](255) NOT NULL,
	[full_name] [nvarchar](255) NULL,
	[gender] [varchar](255) NULL,
	[identity_card] [varchar](255) NOT NULL,
	[password] [varchar](255) NOT NULL,
	[phone] [varchar](255) NOT NULL,
	[province] [nvarchar](255) NULL,
	[role] [varchar](255) NULL,
 CONSTRAINT [PK__users__3213E83FE3073D02] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK26bl9ms0sjsk50osog8mhmq5i] UNIQUE NONCLUSTERED 
(
	[identity_card] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK6dotkott2kjsp8vw4d0m25fb7] UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Index [idx_user_id]    Script Date: 5/12/26 3:39:36PM ******/
CREATE NONCLUSTERED INDEX [idx_user_id] ON [dbo].[accounts]
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [UK6kplolsdtr3slnvx97xsy2kc8]    Script Date: 5/12/26 3:39:36PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [UK6kplolsdtr3slnvx97xsy2kc8] ON [dbo].[accounts]
(
	[account_number] ASC
)
WHERE ([account_number] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
/****** Object:  Index [idx_user_id]    Script Date: 5/12/26 3:39:36PM ******/
CREATE NONCLUSTERED INDEX [idx_user_id] ON [dbo].[beneficiaries]
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
/****** Object:  Index [idx_user_id]    Script Date: 5/12/26 3:39:36PM ******/
CREATE NONCLUSTERED INDEX [idx_user_id] ON [dbo].[notifications]
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [idx_user_type]    Script Date: 5/12/26 3:39:36PM ******/
CREATE NONCLUSTERED INDEX [idx_user_type] ON [dbo].[notifications]
(
	[user_id] ASC,
	[type] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
/****** Object:  Index [idx_saved_receiver_target_account_id]    Script Date: 5/12/26 3:39:36PM ******/
CREATE NONCLUSTERED INDEX [idx_saved_receiver_target_account_id] ON [dbo].[saved_receiver_accounts]
(
	[target_account_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
/****** Object:  Index [idx_saved_receiver_user_id]    Script Date: 5/12/26 3:39:36PM ******/
CREATE NONCLUSTERED INDEX [idx_saved_receiver_user_id] ON [dbo].[saved_receiver_accounts]
(
	[user_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
/****** Object:  Index [uk_saved_receiver_user_target_account]    Script Date: 5/12/26 3:39:36PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [uk_saved_receiver_user_target_account] ON [dbo].[saved_receiver_accounts]
(
	[user_id] ASC,
	[target_account_id] ASC
)
WHERE ([user_id] IS NOT NULL AND [target_account_id] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
/****** Object:  Index [idx_from_and_to_account_id]    Script Date: 5/12/26 3:39:36PM ******/
CREATE NONCLUSTERED INDEX [idx_from_and_to_account_id] ON [dbo].[transactions]
(
	[from_account_id] ASC,
	[to_account_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
/****** Object:  Index [idx_to_account_id]    Script Date: 5/12/26 3:39:36PM ******/
CREATE NONCLUSTERED INDEX [idx_to_account_id] ON [dbo].[transactions]
(
	[to_account_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
GO
ALTER TABLE [dbo].[accounts]  WITH CHECK ADD  CONSTRAINT [FKnjuop33mo69pd79ctplkck40n] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[accounts] CHECK CONSTRAINT [FKnjuop33mo69pd79ctplkck40n]
GO
ALTER TABLE [dbo].[beneficiaries]  WITH CHECK ADD  CONSTRAINT [FKk8iehn8e7itlnc8pev97p1bty] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[beneficiaries] CHECK CONSTRAINT [FKk8iehn8e7itlnc8pev97p1bty]
GO
ALTER TABLE [dbo].[notifications]  WITH CHECK ADD  CONSTRAINT [FK9y21adhxn0ayjhfocscqox7bh] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[notifications] CHECK CONSTRAINT [FK9y21adhxn0ayjhfocscqox7bh]
GO
ALTER TABLE [dbo].[saved_receiver_accounts]  WITH CHECK ADD  CONSTRAINT [FKluo00rjfittv0cbaqb4y1ewb8] FOREIGN KEY([user_id])
REFERENCES [dbo].[users] ([id])
GO
ALTER TABLE [dbo].[saved_receiver_accounts] CHECK CONSTRAINT [FKluo00rjfittv0cbaqb4y1ewb8]
GO
ALTER TABLE [dbo].[accounts]  WITH NOCHECK ADD  CONSTRAINT [CK__accounts__status__4E88ABD4] CHECK  (([status]='SUSPENDED' OR [status]='INACTIVE' OR [status]='ACTIVE'))
GO
ALTER TABLE [dbo].[accounts] CHECK CONSTRAINT [CK__accounts__status__4E88ABD4]
GO
ALTER TABLE [dbo].[notifications]  WITH NOCHECK ADD  CONSTRAINT [CK__notificati__type__534D60F1] CHECK  (([type]='ALERT' OR [type]='MARKETING' OR [type]='TRANSACTION'))
GO
ALTER TABLE [dbo].[notifications] CHECK CONSTRAINT [CK__notificati__type__534D60F1]
GO
USE [master]
GO
ALTER DATABASE [WebBanking_South] SET  READ_WRITE 
GO
